spring.application.name=node_b_worker
server.port=8083

spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


app.sms.queue=sms.queue
app.admin.queue=admin.queue

spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.username=${EMAIL_USER_LOGIN}
spring.mail.password=${EMAIL_USER_PASSWORD}

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.yandex.ru

spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG

